version: "3"

services:
  broker:
    image: eclipse-mosquitto
    hostname: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - broker_network

  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
    env_file:
      - .env
    volumes:
      - ./localdb/myInfluxVolume:/var/lib/influxdb2
    networks:
      - db_network

  grafana:
    image: grafana/grafana
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2023
      - INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - "80:3000"
    volumes:
      - ./localdb/myGrafanaVolume:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - db_network

  app:
    image: adapter
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DEBUG_DATA_FLOW=true
    depends_on:
      - broker
      - influxdb
    networks:
      - db_network
      - broker_network
    env_file:
      - .env

networks:
  db_network:
  broker_network:
